FORMAT: 1A
HOST: https://api.amvse.com/

# Amvse

This is the API for Amvse. It's pretty basic for now, but you have to use it to manage your Amvse websites.

## Authentication [/sessions]

### Create New Session [POST]

Before you can use the Amvse API, you need to login. When you login, you'll receive an API token to authenticate your requests.

+ Request (application/json)

        {
            "username": "YOUR@EMAIL-PROVIDER.COM",
            "password": "YOUR_SECRET_PASSWORD"
        }

+ Response 200 (application/json)

        {
            "token": "YOUR_API_TOKEN"
        }

## Websites [/websites]