FORMAT: 1A
HOST: https://api.amvse.com/v1

# Amvse

This is the API for Amvse. It's pretty basic for now, but you have to use it to manage your Amvse websites.

This documentation covers `v1` of this API. Do note the `/v1` URL prefix.

All requests should be sent to `https://api.amvse.com/v1` followed by the endpoint you'd like to use.

# Group Authentication

All Amvse API requests must be authenticated using HTTP Basic Auth.

Once you've acquired an API token, you should user HTTP Basic Auth with a blank `username` and your API token as the `password`.

## API Token [/sessions]

*This endpoint does not require HTTP Basic Auth.*

### Generate API Token [POST]

Generate a new API Token to authenticate your Amvse API requests.

+ Request (application/json)

        {
            "username": "hello@amvse.com",
            "password": "SUP3R_SECRET_PASSWORD"
        }

+ Response 200 (application/json)

        {
            "token": "SECRET_API_TOKEN"
        }



## Websites [/websites]

**Authentication Required**: HTTP Basic Auth `:$API_TOKEN`

### List All Websites [GET]

+ Response 200 (application/json)

        [
            {
                "realtime_channel_name": "__amvse_Website_1",
                "id": 1,
                "domain_name": "hippota.co",
                "updated_at": "2015-09-14T20:00:40.996-07:00"
            }
        ]
