FORMAT: 1A
HOST: https://api.amvse.com/

# Amvse

This is the API for Amvse. It's pretty basic for now, but you have to use it to manage your Amvse websites.

## Authentication [/sessions]

### Create New Session [POST]

Before you can use the Amvse API, you need to login. When you login, you'll receive an API token to authenticate your requests.

+ Request (application/json)

        {
            "username": "YOUR@EMAIL-PROVIDER.COM",
            "password": "YOUR_SECRET_PASSWORD"
        }

+ Response 200 (application/json)

        {
            "token": "YOUR_API_TOKEN"
        }



## Websites [/websites]

### List All Websites [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]
